### ISSUE TITLE
Design discussion

### ISSUE THREAD

**Issue by amirgon** [amirgon/snippetbin#1]
@embeddedt this is the initial high level design for the [backend service](https://github.com/littlevgl/lvgl/issues/792#issuecomment-515209604).
Please have a look at the [README](https://github.com/amirgon/snippetbin/blob/master/README.md), and let me know if you have any comments.

**Comment by embeddedt** [comment]
Looks good to me; let me know when there's something I can try/help with.

**Comment by amirgon** [comment]
@embeddedt I have something working.  

Please have a look and let me know what you think.
I created a demo client as a reference so you can try it.
Its purpose is to show how to use the REST API and how I imagined the user interface ("Save" and "Copy Link" buttons).

Deployed on Heroku:

- https://snippet-bin.herokuapp.com/
- An example with a few lines and revision history:  
 https://snippet-bin.herokuapp.com/?revision=55402649fb960a131b8e4ca845daffdd9a2ae2a1

**Comment by embeddedt** [comment]
Are the IP addresses in the commit descriptions for https://github.com/amirgon/snippetbin_data going to be showing the IP addresses of the person who saved a file?

**Comment by amirgon** [comment]
> Are the IP addresses in the commit descriptions for https://github.com/amirgon/snippetbin_data going to be showing the IP addresses of the person who saved a file?

Yes.  
And referer and country etc. Could be interesting to log this.

https://github.com/amirgon/snippetbin/blob/a4cd8dcfa0d9f29470517fa0ff3feb1c31402fde/routes/routes.js#L73-L81

**Comment by embeddedt** [comment]
I think we shouldn't be logging that information (especially without asking). That's invasive from a privacy standpoint.

**Comment by amirgon** [comment]
> But other than that, I don't think we should store any other information, or make it publicly accessible (anyone can view the commit history).

The data repo can be private, so only the one who operates the server could see the commit history and access it.  
I think that logging this information internally should be ok, as long as it's not publicly available.  

I think that almost any website you connect to logs IP information this way or another.  
Actually, it's necessary. For example, when you want to blacklist some IP of a spammer, or when someone posts illegal material and you need to report where it came from (otherwise you would be responsible for it).

**Comment by amirgon** [comment]
By the way, there's a ruling that says that [IP addresses in server logs are not personal data](https://www.theregister.co.uk/2008/10/15/ip_address_personal_data_ruling/), and websites are allowed to store them without violating data protection legislation.

Anyway, putting this aside - did you have a chance to look into the REST API and think about integrating it into the js port simulation?  
Did you have a look at the UI (save/ copy buttons, history slider) I susggested in the demo?

Btw I enabled CORS so you could test your code with the REST API on heroku, without the need to deploy the server for now.

**Comment by embeddedt** [comment]
> did you have a chance to look into the REST API and think about integrating it into the js port simulation?
Did you have a look at the UI (save/ copy buttons, history slider) I susggested in the demo?

I looked at it the day you gave me the link. Today I'm going to try and make it work with the JS port.

**Comment by amirgon** [comment]
@embeddedt the deployed server (https://snippet-bin.herokuapp.com) now persists the data.  
Data is automatically reflected on https://github.com/amirgon/snippetbin_data (throttling, so updates could be delayed ~5 minutes until they appear there).

So we can share examples now, without them disappearing:
-  https://snippet-bin.herokuapp.com/?revision=bd070c924974502d6f9161674c4eb83dc44e83e7

**Comment by embeddedt** [comment]
> The deployed server (https://snippet-bin.herokuapp.com) now persists the data.

Great! Can you make the `snippetbin_data` repository private (so that people's IP addresses aren't displayed to the world)?

> Today I'm going to try and make it work with the JS port.

I did get it to work, but I have to serve it on a different CDN (Statically has stopped working properly for some reason).

I won't be able to look at it again until this weekend.

**Comment by amirgon** [comment]
> Great! Can you make the `snippetbin_data` repository private (so that people's IP addresses aren't displayed to the world)?

Sure! I switched https://snippet-bin.herokuapp.com to a private repo.

Here is an example:
- https://snippet-bin.herokuapp.com/?revision=1af1753647f1401f2e2847b29810a548e214acb1


> I did get it to work, but I have to serve it on a different CDN (Statically has stopped working properly for some reason).

Why don't you try Github-Pages? It's free, easy to use and it will probably work tomorrow :wink:

**Comment by embeddedt** [comment]
> Why don't you try Github-Pages?

GitHub Pages will only serve from the `master` branch, the `gh-pages` branch, or a `docs` folder in the `master` branch.

**Comment by amirgon** [comment]
> GitHub Pages will only serve from the `master` branch, the `gh-pages` branch, or a `docs` folder in the `master` branch.

So this can be solved by a branch/fork.
Then just merge the "upstream" js port into it when needed.

**Comment by embeddedt** [comment]
@amirgon I cannot use GitHub Pages while those dead symlinks we had discussed before are in the `ports/esp32/modules` directory. It will just give a build error.

**Comment by amirgon** [comment]
But you can remove them from the js port, and fork gh pages from the js
port.

**Comment by embeddedt** [comment]
So it's okay to have them not be present on the `lvgl_javascript` branch as long as they are still on `master`?

**Comment by amirgon** [comment]
It's important for me to keep the main branch with as few changes as
possible compared to upstream micropython.

But if you need to add more changes on the js branch - this is fine with me.

**Comment by embeddedt** [comment]
@amirgon Alright. Tomorrow I will make the necessary changes to have it work on `gh-pages`.

**Comment by amirgon** [comment]
lvgl specific discussion continues on littlevgl/lvgl/issues/792
